package com.onourem.android.activity.ui.bottomsheet

import java.io.Serializable

enum class ActionType : Serializable {
    ADD_REMOVE_PLAY_GROUP_MEMBERS,
    PLAY_GROUP_INVITE_LINK,
    EXIT_PLAY_GROUP,
    SEE_PLAY_GROUP_MEMBERS,
    DISMISS,
    UN_FRIEND,
    MAKE_PLAY_GROUP_ADMIN, REMOVE_FROM_PLAY_GROUP, REMOVE_AS_PLAY_GROUP_ADMIN, ADD_REMOVE_PRIVACY_GROUP_MEMBERS, REMOVE_FROM_PRIVACY_GROUP, DELETE_PRIVACY_GROUP, NONE, REJECT_FRIEND_REQUEST, REJECT_WATCHLIST_FRIEND_REQUEST, CREATE_QUESTION, QUESTION_PLAYED, QUESTIONS_CREATED, SOLO_GAMES, FRIENDS_PLAYING,  //Watchlist
    REMOVE_FROM_WATCHLIST,  //Image/Video
    PHOTO_LIBRARY, VIDEO_LIBRARY, PHOTO_CAMERA, VIDEO_CAMERA,  //ONE TO MANY
    DELETE_MY_ANSWER, EDIT_GAME_VISIBILITY, DELETE_COMMENT, REPORT_INAPPROPRIATE, IRRELEVANT_RESPONSE, IGNORE,  //DToOne
    DELETE_GAME, CANCEL_GAME,  // TASK & MESSAGE
    REPORT_ABUSE, CANCEL_FRIEND_REQUEST, EDIT_QUESTION, DELETE_QUESTION, DELETE_QUESTION_CONFIRMATION, IGNORE_QUESTION, IGNORE_QUESTION_CONFIRMATION, EDIT_PRIVACY, DELETE_AUDIO, DELETE_AUDIO_CONFIRMATION, STATS, SHOW_AUDIOS_OF_THIS_USERS, SHARE_AUDIO_LINK, REPORT_INAPPROPRIATE_CONFIRM, AUDIO_EDIT_YES, AUDIO_EDIT_NO, AUDIO_UPDATE_TITLE, AUDIO_TRENDING, AUDIO_FRIENDS, AUDIO_MY_VOCALS, AUDIO_FAVORITE, AUDIO_FOLLOW, AUDIO_UNFOLLOW, EXIT_SCREEN, EXIT_SCREEN_CONFIRMATION, BLOCK, BLOCK_REPORT,  //message
    MESSAGE_COPY, MESSAGE_DELETE, SEND_PRIVATE_MESSAGE, VOCALS_BY_USER, VOCALS_BY_TITLE, GUEST, MULTIPLE_CONTACT, PLAY_WITH_SAME_FRIENDS, PLAY_WITH_NEW_FRIENDS,

    ONLINE, OFFLINE, NOT_REQUIRED,


    //admin
    AUDIO_PENDING,
    AUDIO_APPROVED_SCHEDULED,
    AUDIO_APPROVED_PUBLISHED,
    AUDIO_APPROVED_UN_SCHEDULED,
    AUDIO_BLACKLISTED,
    AUDIO_OTHER,
    AUDIO_BLACKLISTED_CONFIRMATION,
    EDIT_SCHEDULE,
    EDIT_RATINGS,
    AUDIO_REMOVE_FROM_TV,
    AUDIO_ADD_TO_BLACKLIST,
    REJECT_AUDIO_CONFIRMATION,
    YOUTUBE_VIDEO

}